# Site settings
title: 东游西荡的老温
description: 码字的地儿
author: 老温
url: "https://pwen.github.io"
baseurl: ""

# Build settings
markdown: kramdown
theme: null
permalink: /:year-:month-:day-:title/

# Languages
languages: ["en", "zh"]
default_lang: "zh"
exclude_from_localization: ["assets", "css", "js"]

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:year-:month-:day-:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Keep tags data in the build
keep_files:
  - assets/tags-data.json

# Timezone
timezone: America/Los_Angeles
